name : football_dbt
version : 1.0
profile : football_dbt

models : 
  football_dbt :
    staging : 
      +schema: staging
      +materialized: view
    marts :
      +schema: marts
      +materialized: table